---


- name: Upload Artifacts
  hosts: "{{ target_host }}"
  gather_facts: no
  become: yes

  tasks:
    - name: Create Folder
      file:
        path: /home/gitlab-runner/artifacts/
        state: directory

    - name: Copy Artifact
      copy:
        src: "/tmp/{{ artifact_name }}"
        dest: "/home/gitlab-runner/artifacts/{{ artifact_name }}"
        backup: yes
        group: root
        owner: root
